apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "kuma-nodeport" | quote }}
  namespace: {{ .Values.kuma.namespace | default "kuma" | quote }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}  
  ports:
  - protocol: TCP
    port: 3001   
    targetPort: 3001  
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort | default 33000 }}   
    {{- end }}
  selector:
    app: kuma

